name: Auto Assign Backlog → To Do & In Progress → In Review
on:
    project_card:
        types: [moved]

permissions:
    issues: write

jobs:
    assign:
        runs-on: ubuntu-latest
        steps:
            - name: Detectar movimiento de columna
              run: |
                DESTINO=${{ github.event.project_card.column_id }}
                ID_TO_DO="61e4505c"
                ID_IN_REVIEW="df73e18b"

                if [ "$DESTINO" = "$ID_TO_DO" ]; then
                echo "Movimiento Backlog → To Do"
                echo "fase=todo" >> $GITHUB_ENV
                elif [ "$DESTINO" = "$ID_IN_REVIEW" ]; then
                echo "Movimiento In Progress → In Review"
                echo "fase=review" >> $GITHUB_ENV
                else
                    echo "Movimiento no relevante, saliendo..."
                    exit 0
                fi

            - name: Elegir integrante al azar
              id: random
              run: |
                if [ "$fase" = "todo" ]; then
                    USERS=("usuario1" "usuario2" "usuario3" "usuario4")
                elif [ "$fase" = "review" ]; then
                    USERS=("usuario5" "usuario6" "usuario7" "usuario8")
                fi
                RANDOM_USER=${USERS[$RANDOM % ${#USERS[@]}]}
                echo "assignee=$RANDOM_USER" >> $GITHUB_OUTPUT

            - name: Asignar issue
              uses: peter-evans/assign-issue@v2
              with:
                assignees: ${{ steps.random.outputs.assignee }}
